project_id = "sefwgqtthvrmwcnanncr"

[functions.access-submit]
verify_jwt = false

[functions.access-signin]
verify_jwt = false

[functions.access-approve]
verify_jwt = false

[functions.access-resend]
verify_jwt = false

[functions.access-reject]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false
